name: Optimizely Flags Notifier
description: Recieve a slack notification with a list of flags that haven't been updated in a while.

author: Hitarth Desai <hitarthdesai306@gmail.com>

branding:
  icon: 'flag'
  color: 'gray-dark'

inputs:
  optimizely_project_id:
    description: The Optimizely project ID for which the action should generate the report.
    required: true
  optimizely_auth_token:
    description: The Optimizely API token for authentication. It is used to fetch the flags and their last updated time.
    required: true
  slack_channel_id:
    description: The Slack channel ID to which the action will send a message with the report.
    required: true
  slack_app_bot_token:
    description: The Slack app bot token for authentication. It is used to fetch the user name and profile picture of the bot.
    required: true

runs:
  using: node16
  main: dist/index.js