name: Test Optimizely Flags Notifier Action

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Action
        uses: hitarthdesai/optimizely-flags-notifier@v0.2.3
        with:
          optimizely_project_id: ${{ secrets.OPTIMIZELY_PROJECT_ID }}
          optimizely_auth_token: ${{ secrets.OPTIMIZELY_AUTH_TOKEN }}
          slack_app_bot_token: ${{ secrets.SLACK_APP_BOT_TOKEN }}
          slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
